backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
logo_url: /img/nntv_logo_black.png

collections:   
  - name: "siteComponents"
    label: "Site Components"
    preview: true
    files:
      - file: "src/pages/siteComponents/seo/index.md"
        label: "SEO"
        name: "seo"
        fields:
          - { label: "Site Title", name: "siteTitle", widget: string }
          - { label: "Site Description", name: "siteDescription", widget: string }
          - { label: "Favicon Color", name: "faviconColor", widget: color, picker: sketch, enableAlpha: false }
      - file: "src/pages/siteComponents/nav-bar/index.md"
        label: "Navigation Bar"
        name: "nav-bar"
        fields:
          [
            { label: "Brand Image", name: "brandImage", widget: image },
            { label: "Alt Text", name: "brandImageAlt", widget: string },
            { label: "Navigation Bar Color", name: "navBarColor", widget: color, picker: sketch, enableAlpha: true },
            { 
              name: "nav-bar-alignment",
              label: "Navigation Bar Alignment",
              widget: inline-select,
              required: false,
              options:
                [
                  { label: Left, value: left},
                  { label: Center, value: center},
                  { label: Right, value: right},
                ]
            },
            {
              label: "Navigation Item",
              name: "navItem",
              widget: list,
              required: false,
              fields:
                [
                  { label: "Page Name", name: "pageName", widget: string, required: false },
                  { label: "Page URL", name: "pageURL", widget: string, required: false },
                  {
                    label: "Sub-Navigation Item",
                    name: "subNavItem",
                    widget: list,
                    required: false,
                    fields:
                      [
                        { label: "Page Name", name: "subPageName", widget: string, required: false },
                        { label: "Page URL", name: "subPageURL", widget: string, required: false },
                        {
                          label: "Sub-Navigation Inner Item",
                          name: "subSubNavItem",
                          widget: list,
                          required: false,
                          fields:
                            [
                              { label: "Page Name", name: "subSubPageName", widget: string, required: false },
                              { label: "Page URL", name: "subSubPageURL", widget: string, required: false },
                            ],
                        }
                      ],
                  },
                  { label: "Enable", name: "navItemToggle", widget: "boolean", default: true, required: false },
                ],
            },
            
            
          ]
      - file: "src/pages/siteComponents/branding/index.md"
        label: "Branding"
        name: "branding"
        fields:
          - { label: "Logo Image", name: "logoImage", widget: image }
  
  - name: "course"
    label: "Course"
    folder: "src/pages/course"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "course-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Introduction", name: "introduction", widget: "text" }
      - { label: "Course Thumbnail", name: "coursethumbnail", widget: image }
      - { label: "Duration (Min)", name: "duration", widget: "number" }
      - { 
          name: "level",
          label: "Level",
          widget: inline-select,
          required: false,
          options:
            [
              { label: Beginner, value: beginner},
              { label: Intermediate, value: intermediate},
              { label: Advanced, value: advanced},
            ]
        }
      - { label: "Number of Modules", name: "numberofmodules", widget: "number", required: false }
      - { label: "Resources", name: "resources", widget: "string", required: false }
      - { label: "Require Access To", name: "Requireaccessto", widget: "string", required: false }
      - { label: "About", name: "about", widget: "text", required: false }
      - { label: "Outcomes", name: "outcomes", widget: "text", required: false }
      - {
          label: Modules,
          name: modules,
          widget: list,
          fields:
            [
              { label: "Lessons",
                name: "lessons",
                widget: relation,
                collection: "module",
                displayFields: ["title"],
                searchFields: ["title"],
                valueField: "title"
              }
            ]
        }
      
    
  - name: "module"
    editor:
      preview: false
    label: "Module"
    folder: "src/pages/module"
    create: true
    slug: "{{slug}}"
    fields:
      [
        {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "module-page",
        },
        { label: "Title", name: "title", widget: string },
        { label: "Video Thumbnail", name: "videothumbnail", widget: image },
        { label: "Video Link", name: "videolink", widget: string },
        { label: "Script", name: "script", widget: text },
        { label: "Credit & Info", name: "creditandinfo", widget: text },
      ]
      


  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Movie, name: movie, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: "Yellow Title", name: yellowtitle, widget: string }
          - { label: "Yellow Paragraph", name: yellowparagraph, widget: text }
      - file: "src/pages/our-vision/index.md"
        label: "About"
        name: "our-vision"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "featuredimage", widget: image }
          - { label: "Opening Paragraph", name: "openingparagraph", widget: "text" }
          - { label: "Opening Tagline", name: "openingtagline", widget: "string" }
          - { label: "Secondary Title", name: "secondarytitle", widget: "string" }
          - { label: "Secondary Tagline", name: "secondarytagline", widget: "string" }
          - { label: "See More Button Text", name: "seemoretext", widget: "string" }
          - {
              label: Values,
              name: values,
              widget: list,
              fields:
                [
                  { label: "Value Title", name: "valuetitle", widget: string },
                  { label: "Value Paragraph", name: "valueparagraph", widget: string },
                  { label: "Value Image", name: "valueimage", widget: image },
                ]
            }
          - { label: "Tertiary Title", name: "tertiarytitle", widget: "string" }
          - { label: "Tertiary Paragraph", name: "tertiaryparagraph", widget: "text" }
          - {
              label: Members,
              name: members,
              widget: list,
              fields:
                [
                  { label: "Member Name", name: "membername", widget: string },
                  { label: "Member Bio", name: "memberbio", widget: text, required: false },
                  { 
                    name: "memberimagealign",
                    label: "Member Image Alignment",
                    widget: inline-select,
                    required: false,
                    options:
                      [
                        { label: Left, value: left},
                        { label: Center, value: center},
                        { label: Right, value: right},
                      ]
                  },
                  { label: "Member Image", name: "memberimage", widget: image, required: false },
                ]
            }
      - file: "src/pages/under-construction/index.md"
        label: "Under Construction"
        name: "under-construction"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "under-construction",
            }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Subtext", name: "subtext", widget: "string" } 
