backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
logo_url: /img/nntv_logo_black.png

collections:   
  - name: "siteComponents"
    label: "Site Components"
    preview: true
    files:
      - file: "src/pages/siteComponents/nav-bar/index.md"
        label: "Navigation Bar"
        name: "nav-bar"
        fields:
          [
            { label: "Brand Image", name: "brandImage", widget: image },
            { label: "Alt Text", name: "brandImageAlt", widget: string },
            { label: "Navigation Bar Color", name: "navBarColor", widget: color, picker: sketch, enableAlpha: true },
            { 
              name: "nav-bar-alignment",
              label: "Navigation Bar Alignment",
              widget: inline-select,
              required: false,
              options:
                [
                  { label: Left, value: left},
                  { label: Center, value: center},
                  { label: Right, value: right},
                ]
            },
            {
              label: "Navigation Item",
              name: "navItem",
              widget: list,
              required: false,
              fields:
                [
                  { label: "Page Name", name: "pageName", widget: string, required: false },
                  { label: "Page URL", name: "pageURL", widget: string, required: false },
                  {
                    label: "Sub-Navigation Item",
                    name: "subNavItem",
                    widget: list,
                    required: false,
                    fields:
                      [
                        { label: "Page Name", name: "subPageName", widget: string, required: false },
                        { label: "Page URL", name: "subPageURL", widget: string, required: false },
                        {
                          label: "Sub-Navigation Inner Item",
                          name: "subSubNavItem",
                          widget: list,
                          required: false,
                          fields:
                            [
                              { label: "Page Name", name: "subSubPageName", widget: string, required: false },
                              { label: "Page URL", name: "subSubPageURL", widget: string, required: false },
                            ],
                        }
                      ],
                  },
                  { label: "Enable", name: "navItemToggle", widget: "boolean", default: true, required: false },
                ],
            },
            
            
          ]
      - file: "src/pages/siteComponents/branding/index.md"
        label: "Branding"
        name: "branding"
        fields:
          - { label: "Logo Image", name: "logoImage", widget: image }
      

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Keywords,
              name: keywords,
              widget: list,
              fields:
                [
                  { label: Word, name: word, widget: string },
                ],
            }
          - { label: "Yellow Title", name: yellowtitle, widget: string }
          - { label: "Yellow Paragraph", name: yellowparagraph, widget: string }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/our-vision/index.md"
        label: "Our Vision"
        name: "our-vision"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "featuredimage", widget: image }
          - { label: "Opening Paragraph", name: "openingparagraph", widget: "string" }
          - { label: "Opening Tagline", name: "openingtagline", widget: "string" }
          - { label: "Secondary Title", name: "secondarytitle", widget: "string" }
          - { label: "Secondary Tagline", name: "secondarytagline", widget: "string" }
          - { label: "See More Button Text", name: "seemoretext", widget: "string" }
          - {
              label: Values,
              name: values,
              widget: list,
              fields:
                [
                  { label: "Value Image", name: "valueimage", widget: image },
                  { label: "Value Title", name: "valuetitle", widget: string },
                  { label: "Value Paragraph", name: "valueparagraph", widget: string },
                ]
            }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "src/pages/under-construction/index.md"
        label: "Under Construction"
        name: "under-construction"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "under-construction",
            }
          - { label: "Header", name: "header", widget: "string" }
          - { label: "Subtext", name: "subtext", widget: "string" } 
